const CUBRID_DATABASE_HOST = "127.0.0.1";
const CUBRID_DATABASE_USER = "dba";
const CUBRID_DATABASE_PASS = "";
const CUBRID_DATABASE_PORT = "30000";
const CUBRID_DATABSE_CHARSET = "utf8";
const CUBRID_DATABASE_NAME = "demodb";